### ISSUE TITLE
ConstSet/FlexSet

### ISSUE THREAD

**Issue by washort** [monte-language/monte#10]
We don't have a set type yet. It'd be handy.

**Comment by dckc** [comment]
I suggest closing this: we seem to have ConstSet and FlexSet now.

https://github.com/monte-language/typhon/blob/master/typhon/objects/collections.py#L791
https://github.com/monte-language/typhon/commit/c48c0a7e038620292b8b306eef1fc78ed688480e

note also `_flexSet = getGlobal(u"_flexSet")`

Perhaps this should stay open until there are docs and tests, though.

Meanwhile, I gather stdlib issues should go on the typhoon repo now.
