### ISSUE TITLE
'object foo :SomeGuard {}' should be a syntax error

### ISSUE THREAD

**Issue by washort** [monte-language/monte#14]
Objects use `as` to declare the auditor and guard for their binding, a too-permissive syntax rule allows the guard syntax from name patterns here, but the compiler ignores it.

Note that `interface Foo :SomeGuard {}` should remain legal.

**Comment by dckc** [comment]
this seems to be fixed:

```
<DanC_> > object foo :SomeGuard {}
<airbrus> [expected {, got :, <<eval>#:span::1:7:1:10>]

<DanC_> > interface Foo :SomeGuard {}
<airbrus> Keys not in scope: SomeGuard
```
