### ISSUE TITLE
Write example module using all operators

### ISSUE THREAD

**Issue by edunham** [monte-language/monte#22]
List of operators is available in the parser at https://github.com/monte-language/monte/blob/master/monte/parser.py#L39

Please write a module that demonstrates each operator, documents its precedence and name in comments, and includes tests for a couple simple uses of the operator. This will go in monte/src/examples. 

Examples of how to write a module with tests will be in testing.mt if it works. Otherwise this is blocked on somebody getting it working.

**Comment by dckc** [comment]
#63 is another approach: extract test cases from the docs.
