### ISSUE TITLE
Help Java users get on their feet (and make sure the parser can deal with it)

### ISSUE THREAD

**Issue by MostAwesomeDude** [monte-language/monte#38]
Monte has a simpler approach to object composition and inheritance than many other object-based and object-oriented languages. Instead of classes or prototypes, Monte has a simple single syntax for constructing objects, the ``object`` expression.

```monte
object myObject:
    pass
```

Unlike Java, Monte objects are not constructed from classes. Unlike JavaScript or Python, Monte objects are not constructed from prototypes. As a result, it might not be obvious at first how to build multiple objects which are similar in behavior. However, Monte has a very simple idiom for class-like constructs.

```monte
def makeMyObject():
    return object myObject:
        pass
```

Methods can be attached to objects with the ``to`` keyword.

```monte
object deck:
    to size():
        return 52
```

Finally, just like with functions, methods can have guards on their parameters and return value.

```monte
object deck:
    to size(suits :int, ranks :int) :int:
        return suits * ranks
```

**Comment by edunham** [comment]
Added this information to the docs in https://github.com/monte-language/monte/pull/42 . That should probably be sufficient to assist new users coming from Java-land?

**Comment by edunham** [comment]
Confirmed that the documentation is adequate to resolve this issue.
