### ISSUE TITLE
pygments lexer for monte

### ISSUE THREAD

**Issue by dckc** [monte-language/monte#53]
it seems to be referenced by the sphinx doc but not yet defined

**Comment by MostAwesomeDude** [comment]
Upstream Pygments now has a Monte lexer.

**Comment by dckc** [comment]
promoted from IRC:

simpson> DanC: One non-entry-level thing that I *do* want to do is figure out how to get Sphinx to use the "monte" lexer from Pygments by default.
simpson> I think that the currently-released Pygments version includes the Monte patches that I wrote a while ago.
simpson> Aw, nope, my patches were merged in June but a release was last cut in March.

DanC> customizing rtd to use an unreleased pygments seems like a manageable amount of pain
simpson> I have zero idea how flexible RTD is on this point.
DanC> seems like you could point to your own pygments in a [custom requirements-file](https://docs.readthedocs.io/en/latest/yaml-config.html#requirements-file)
or [python-extra-requirements](https://docs.readthedocs.io/en/latest/yaml-config.html#python-extra-requirements)

**Comment by MostAwesomeDude** [comment]
The feature is well shipped IME; [this pastebin](https://bpa.st/) supports Monte highlighting and looks much better than GH's highlighting.
